name: Build and tests
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - master

  # run tests for all pull requests
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - go: 1.19.x
          - go: 1.12.x

    name: Build Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          go build

      - name: Run Tests
        run: |
          go test ./...
