name: Build and tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
        id: go

      - name: Get programs
        run: |
          export GOBIN=$HOME/bin
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.19.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          go build

      - name: Run tests
        run: |
          export PATH=$HOME/bin:$PATH
          go test -mod=vendor ./...
